import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/exports";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "HooBank Landing Page",
  description: "Generated by HooBank Ltd..",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
